Repository vmangos/core, pull requests merged in 2021-03, with the labels that each got.

#909 Respawn Caer Darrow
  sql/migrations/20201216203835_world.sql
Labels: bug, missing data

#1031 Broadcast text for the barrens
  sql/migrations/20210128145653_world.sql
  src/scripts/kalimdor/the_barrens/the_barrens.cpp
Labels: bug, missing data, npc

#1036 Misc DB Fixes
  sql/migrations/20210129141529_world.sql
Labels: bug, missing data

#1042 Add nature immunity to some lava elementals
  sql/migrations/20210201011631_world.sql
Labels: bug, missing data

#1053 Fix Some Lunar Festival Bugs
  sql/migrations/20210207112151_world.sql
Labels: bug, event, missing data

#1060 Russian Trainer Greets
  sql/migrations/20210213190413_world.sql
Labels: bug, missing data

#1070 AQ fixes
  sql/migrations/20210218152035_world.sql
  src/game/Spells/Spell.cpp
  src/game/Spells/SpellEffects.cpp
  src/scripts/kalimdor/silithus/ruins_of_ahnqiraj/boss_ayamiss.cpp
  src/scripts/kalimdor/silithus/ruins_of_ahnqiraj/boss_kurinnaxx.cpp
  src/scripts/kalimdor/silithus/ruins_of_ahnqiraj/boss_moam.cpp
  src/scripts/kalimdor/silithus/ruins_of_ahnqiraj/boss_rajaxx.cpp
  src/scripts/kalimdor/silithus/ruins_of_ahnqiraj/instance_ruins_of_ahnqiraj.cpp
  src/scripts/kalimdor/silithus/ruins_of_ahnqiraj/ruins_of_ahnqiraj.cpp
  src/scripts/kalimdor/silithus/ruins_of_ahnqiraj/ruins_of_ahnqiraj.h
  src/scripts/kalimdor/silithus/temple_of_ahnqiraj/boss_skeram.cpp
Labels: dungeon, missing data

#1076 Output mmap navmesh as wavefront 3d obj
  contrib/mmap/readme
  contrib/mmap/src/MapBuilder.cpp
  contrib/mmap/src/MapBuilder.h
Labels: feature, mmap

#1079 Removed unused map_template fields.
  sql/migrations/20210220230709_world.sql
  src/game/Database/SQLStorages.cpp
  src/game/Maps/Map.h
  src/game/Spells/Spell.cpp
Labels: bug, dungeon, feature

#1077 vmap doodad update
  contrib/vmap_extractor/vmapextract/adtfile.cpp
  contrib/vmap_extractor/vmapextract/gameobject_extract.cpp
  contrib/vmap_extractor/vmapextract/vmapexport.cpp
  contrib/vmap_extractor/vmapextract/vmapexport.h
  contrib/vmap_extractor/vmapextract/wmo.cpp
  contrib/vmap_extractor/vmapextract/wmo.h
Labels: feature, mmap

#1080 Only spawn Camp Taurajo flight master in 1.6+.
  sql/migrations/20210222003351_world.sql
Labels: missing data, npc, progression

#1088 Make sure AFK status is removed BEFORE teleporting the player to the BG.
  src/game/Battlegrounds/BattleGround.cpp
  src/game/Battlegrounds/BattleGroundMgr.cpp
Labels: bug

#1099 Fix memory leaks
  src/game/Commands/CreatureCommands.cpp
  src/game/Commands/ObjectCommands.cpp
  src/game/Maps/Map.cpp
  src/game/PacketBroadcast/PlayerBroadcaster.cpp
  src/game/vmap/VMapManager2.cpp
Labels: bug

#1096 Fix Starshards and Curse of Agony
  src/game/Spells/SpellAuras.cpp
  src/shared/Util.cpp
  src/shared/Util.h
Labels: bug, spell

#1109 remove Travis CI
  .travis.yml
  README.md
Labels: support

#1110 copy CMake directives for Windows CI build.
  .github/workflows/vmangos.yml
Labels: support

#1094 Add Justine Demalier Event
  sql/migrations/20210302194837_world.sql
Labels: missing data, npc

#1097 Misc DB Fixes
  sql/migrations/20210303085717_world.sql
Labels: bug

#1090 Add batching for procs and delay most spell effects.
  sql/migrations/20210208100903_world.sql
  sql/migrations/20210217012808_world.sql
  src/game/Handlers/MiscHandler.cpp
  src/game/Objects/GameObject.cpp
  src/game/Objects/Object.cpp
  src/game/Objects/Object.h
  src/game/Objects/Player.cpp
  src/game/Objects/Player.h
  src/game/Objects/Unit.cpp
  src/game/Objects/Unit.h
  src/game/Spells/Spell.cpp
  src/game/Spells/Spell.h
  src/game/Spells/SpellAuras.cpp
  src/game/Spells/SpellDefines.h
  src/game/Spells/SpellEffects.cpp
  src/game/Spells/SpellEntry.cpp
  src/game/Spells/SpellEntry.h
  src/game/Spells/SpellMgr.cpp
  src/game/World.cpp
  src/game/World.h
  src/mangosd/mangosd.conf.dist.in
Labels: feature
