Repository vmangos/core, pull requests merged in 2021-02, with the labels that each got.

#1041 Default to old PCH implementation when using MSVC
  CMakeLists.txt
  src/game/CMakeLists.txt
  src/scripts/CMakeLists.txt
Labels: bug

#808 Spawn The Dark Portal area.
  sql/migrations/20201002171825_world.sql
Labels: bug, missing data

#1009 Add Misc Creature Waypoints
  sql/migrations/20210119165824_world.sql
Labels: bug, missing data

#1045 Fix Razuvious leash height
  src/scripts/eastern_kingdoms/eastern_plaguelands/naxxramas/instance_naxxramas.cpp
Labels: bug, dungeon

#1014 DB PULL REQUEST: Add Threat values to paladin blessings based on the level the spell is learned
  sql/migrations/20210121063854_world.sql
Labels: missing data, spell

#1067 Fix Might of Ragnaros Combat Bug
  sql/migrations/20210217165614_world.sql
  src/scripts/eastern_kingdoms/burning_steppes/molten_core/boss_ragnaros.cpp
Labels: dungeon

#1068 Update Ragnaros' Wrath of Ragnaros Cast to also reset threat like on Classic
  src/scripts/eastern_kingdoms/burning_steppes/molten_core/boss_ragnaros.cpp
Labels: dungeon

#1061 🍰 Removed unused Stuff
  CONTRIBUTING.md
  docs/ISSUE_TEMPLATE.md
Labels: support

#1050 Aura effect fixes
  src/game/Spells/SpellAuras.cpp
Labels: bug

#1052 fix enemy stealth alert ignoring los
  src/game/AI/CreatureAI.cpp
Labels: bug, npc

#1062 Handle running out of file descriptors on linux.
  src/framework/Network/MangosSocket.h
  src/framework/Network/MangosSocketMgr.h
  src/framework/Network/MangosSocketMgrImpl.h
Labels: bug
