Repository vmangos/core, pull requests merged in 2021-01, with the labels that each got.

#962 Spell 29519 (Silithyst) should create Silithyst Mound (181597) on Cancel Aura
  src/game/Spells/SpellAuras.cpp
Labels: bug, spell

#960 Fix Terrordale Haunting Spirit Gameobject
  sql/migrations/20210102160021_world.sql
Labels: bug, spell

#903 Update Vendors - Stonetalon Mountains, Durotar, Orgrimmar, The Barrens, Desolace and Thunder Bluff
  sql/migrations/20201211153803_world.sql
Labels: bug, missing data

#973 escaped some core mysql queries
  src/game/Battlegrounds/BattleGroundMgr.cpp
  src/game/Chat/AsyncCommandHandlers.cpp
  src/game/Chat/MasterPlayer.cpp
  src/game/Commands/MiscCommands.cpp
  src/game/Handlers/CharacterHandler.cpp
  src/game/Handlers/MiscHandler.cpp
  src/game/Objects/Pet.cpp
  src/game/PlayerBots/PlayerBotMgr.cpp
  src/game/WorldSession.cpp
  src/mangosd/ChatSocket.cpp
Labels: feature

#965 Update boss_ouro.cpp
  src/scripts/kalimdor/silithus/temple_of_ahnqiraj/boss_ouro.cpp
Labels: bug, dungeon

#968 Silithus world pvp fixes
  sql/migrations/20210104121750_world.sql
  sql/migrations/20210105084615_world.sql
  sql/migrations/20210105091011_world.sql
  sql/migrations/20210105114022_world.sql
  src/game/Objects/GameObject.cpp
  src/game/OutdoorPvP/OutdoorPvPSI.cpp
  src/game/OutdoorPvP/OutdoorPvPSI.h
  src/game/Spells/SpellAuras.cpp
  src/game/Spells/SpellEffects.cpp
Labels: bug, spell

#926 Quivers should not increase haste for ammoless ranged weapons.
  src/game/Spells/SpellAuras.cpp
Labels: bug

#743 Update and add NPC movement scripts - Badlands
  sql/migrations/20200802210659_world.sql
Labels: bug, missing data

#910 Broadcast texts for wailing caverns
  sql/migrations/20201217150400_world.sql
  src/scripts/kalimdor/the_barrens/wailing_caverns/wailing_caverns.cpp
Labels: bug, dungeon

#916 Add Pilot Stonegear Script
  sql/migrations/20201221160630_world.sql
Labels: bug

#917 Update Vendors - Thousand Needles, Ungoro Crater, Silithus, Feralas and Tanaris
  sql/migrations/20201222170716_world.sql
Labels: bug, missing data

#918 Correct Flags for Mining, Skinning and Herbalism Trainers
  sql/migrations/20201222170619_world.sql
Labels: bug

#919 Update Creatures and Scripts - Tanaris, Feralas, Silithus, Un' goro and Thousand Needles
  sql/migrations/20201224122604_world.sql
Labels: bug, missing data

#924 Denalan's Earth (997) - Improve quest_end_script
  sql/migrations/20201228205225_world.sql
Labels: bug, quest

#941 Add Gnomeregan Escape Event
  sql/migrations/20201231164608_world.sql
Labels: bug, missing data

#947 Add missing Blindweed spawns
  sql/migrations/20210102155603_world.sql
Labels: bug, missing data

#948 Add missing Dreamfoil spawns
  sql/migrations/20210102160847_world.sql
Labels: bug, missing data

#949 Add missing Earthroot spawns
  sql/migrations/20210102161211_world.sql
Labels: bug, missing data

#950 Add missing Fadeleaf spawns
  sql/migrations/20210102161652_world.sql
Labels: bug, missing data

#951 Add missing Goldthorn spawns
  sql/migrations/20210102162126_world.sql
Labels: bug, missing data

#952 Add missing Khadgar's Whisker spawns
  sql/migrations/20210102163421_world.sql
Labels: bug, missing data

#953 Add missing Kingsblood spawns
  sql/migrations/20210102163734_world.sql
Labels: bug, missing data

#954 Add missing Liferoot spawns
  sql/migrations/20210102164029_world.sql
Labels: bug, missing data

#955 Add missing Mountain Silversage spawns
  sql/migrations/20210102164332_world.sql
Labels: bug, missing data

#956 Add missing Silverleaf spawns
  sql/migrations/20210102164621_world.sql
Labels: bug, missing data

#957 Add missing Stranglekelp spawns
  sql/migrations/20210102164919_world.sql
Labels: bug, missing data

#958 Add missing Sungrass spawns
  sql/migrations/20210102165217_world.sql
Labels: bug, missing data

#959 Add missing Wild Steelbloom spawns
  sql/migrations/20210102165532_world.sql
Labels: bug, missing data

#977 Add rejuvenation spell when eating deviate fish, improve spell effect "Party Time"
  src/game/Spells/SpellAuras.cpp
  src/game/Spells/SpellEffects.cpp
Labels: missing data, spell

#972 Add Misc Creature Waypoints
  sql/migrations/20210105165912_world.sql
Labels: bug, missing data, npc

#983 Update Quest Chain 1070
  sql/migrations/20210108174134_world.sql
Labels: bug, quest

#991 Fix Tome of Divinity Quest Chains (Again)
  sql/migrations/20210110171501_world.sql
Labels: bug, quest

#940 Quest: Counterattack! - use broadcast texts, added sound
  sql/migrations/20201215291449_world.sql
  src/scripts/kalimdor/the_barrens/the_barrens.cpp
Labels: bug, event, missing data, quest

#980 Fix Lexlort gossip
  sql/migrations/20210107205655_world.sql
Labels: bug, npc, spell

#981 The rethban gauntlet startscript
  sql/migrations/20210107222838_world.sql
Labels: bug, missing data, quest

#993 Fix Brood of Nozdormu Quest Chains
  sql/migrations/20210111181621_world.sql
Labels: bug, quest

#995 Fix Childrens Week Quest Chains
  sql/migrations/20210113090439_world.sql
Labels: bug, quest

#1005 Fix quest requirement for Scarab Shells pre 1.3
  sql/migrations/20210117211419_world.sql
Labels: bug, quest

#1006 Remove XP reward from Heroes of Darrowshire pre 1.3
  sql/migrations/20210117211849_world.sql
Labels: bug, quest

#1007 Fix Mooncloth pattern pre 1.3
  sql/migrations/20210118014808_world.sql
Labels: bug, missing data

#1008 Fix Test of Skulls quests pre 1.3
  sql/migrations/20210118151528_world.sql
Labels: bug, missing data, quest

#1013 Allow spells which have resistance modifier as first effect to be considered binary spells.
  src/game/Spells/SpellEntry.cpp
Labels: feature, spell

#1032 Add legacy cmake support for PCH.
  CMakeLists.txt
  cmake/FindPCHSupport.cmake
  src/game/CMakeLists.txt
  src/game/pchdef.cpp
  src/game/pchdef.h
  src/scripts/CMakeLists.txt
  src/scripts/PrecompiledHeaders/scriptPCH.cpp
Labels: feature

#1030 Reworked droprate of [Recipe: Savory Deviate Delight] from barrens npcs
  sql/migrations/20210128123217_world.sql
Labels: bug, missing data

#1034 Item description locales for german clients
  sql/migrations/20210128210351_world.sql
Labels: bug, missing data

#1035 Cmake
  CMakeLists.txt
  src/CMakeLists.txt
  src/game/CMakeLists.txt
  src/mangosd/CMakeLists.txt
  src/scripts/CMakeLists.txt
Labels: bug, feature

#1039 PlayerWrapper: declare template specialization in header
  src/game/Chat/AbstractPlayer.cpp
  src/game/Chat/AbstractPlayer.h
Labels: bug

#1037 Quality Colors for GetItemLink & ItemLookup
  src/game/Chat/Chat.cpp
  src/game/Commands/LookupCommands.cpp
Labels: feature
