Repository vmangos/core, pull requests merged in 2021-04, with the labels that each got.

#1108 added default mkdir mmaps to MoveMapGen
  contrib/mmap/src/generator.cpp
Labels: bug, mmap

#1043 Improved formula for combat skill increase
  src/game/Objects/Player.cpp
  src/game/Objects/Player.h
  src/game/Objects/Unit.cpp
Labels: bug, feature

#1081 Old dragonkin elites should be elites in pre patch 1.12.0.
  sql/migrations/20210222004851_world.sql
Labels: bug, missing data, npc, progression

#1100 Implement dithering of fractional values
  dep/include/mersennetwister/MersenneTwister.h
  dep/src/gsoap/stdsoap2.cpp
  sql/migrations/20210305185918_characters.sql
  src/game/Commands/UnitCommands.cpp
  src/game/Objects/Object.cpp
  src/game/Objects/Object.h
  src/game/Objects/Pet.cpp
  src/game/Objects/Player.cpp
  src/game/Objects/Player.h
  src/game/Objects/Unit.cpp
  src/game/Objects/Unit.h
  src/game/Spells/Spell.cpp
  src/game/Spells/Spell.h
  src/game/Spells/SpellAuras.cpp
  src/game/Spells/SpellAuras.h
  src/game/Spells/SpellEffects.cpp
  src/game/UnitAuraProcHandler.cpp
  src/mangosd/soapC.cpp
  src/scripts/eastern_kingdoms/burning_steppes/blackwing_lair/boss_nefarian.cpp
  src/scripts/eastern_kingdoms/burning_steppes/molten_core/boss_baron_geddon.cpp
  src/scripts/eastern_kingdoms/eastern_plaguelands/eastern_plaguelands.cpp
  src/scripts/eastern_kingdoms/eastern_plaguelands/naxxramas/boss_four_horsemen.cpp
  src/shared/Util.cpp
  src/shared/Util.h
Labels: bug

#1101 Add Bloodhoof Village Training Event
  sql/migrations/20210306182435_world.sql
Labels: event, missing data
